const images = {
  ic_follow_empty : require('../icons/follow_empty.png'),
  avatar : require('../icons/user_empty_avatar.png'),
  ic_artwork: require('../icons/ic_artwork.png'),
  ic_back: require('../icons/ic_back.png'),
  ic_camera: require('../icons/ic_camera.png'),
  ic_camera_access: require('../icons/ic_camera_access.png'),
  ic_close: require('../icons/ic_close.png'),
  ic_discover: require('../icons/ic_discover.png'),
  ic_down: require('../icons/ic_down.png'),
  ic_facebook: require('../icons/ic_facebook.png'),
  ic_facebook_disable: require('../icons/ic_facebook_disable.png'),
  ic_fail: require('../icons/ic_fail.png'),
  ic_go_to: require('../icons/ic_go_to.png'),
  ic_google: require('../icons/ic_google.png'),
  ic_identify: require('../icons/ic_identify.png'),
  ic_images: require('../icons/ic_images.png'),
  ic_instagram: require('../icons/ic_instagram.png'),
  ic_instagram_disable: require('../icons/ic_instagram_disable.png'),
  ic_journey_new: require('../icons/ic_journey_new.png'),
  ic_like: require('../icons/ic_like.png'),
  ic_line_follow: require('../icons/ic_line_follow.png'),
  ic_linkedin: require('../icons/ic_linkedin.png'),
  ic_location_gps: require('../icons/ic_location_gps.png'),
  ic_location_wellcome: require('../icons/ic_location_wellcome.png'),
  ic_marker_box: require('../icons/ic_marker_box.png'),
  ic_noti: require('../icons/ic_noti.png'),
  ic_noun_dots: require('../icons/ic_noun_dots.png'),
  ic_noun_school: require('../icons/ic_noun_school.png'),
  ic_photo: require('../icons/ic_photo.png'),
  ic_photo_success: require('../icons/ic_photo_success.png'),
  ic_profile: require('../icons/ic_profile.png'),
  ic_radio_check: require('../icons/ic_radio_check.png'),
  ic_radio_unCheck: require('../icons/ic_radio_unCheck.png'),
  ic_save: require('../icons/ic_save.png'),
  ic_search_wellcome: require('../icons/ic_search_wellcome.png'),
  ic_see_where_follow: require('../icons/ic_see_where_follow.png'),
  ic_see_your_friend: require('../icons/ic_see_your_friend.png'),
  ic_setting: require('../icons/ic_setting.png'),
  ic_sign_up: require('../icons/ic_sign_up.png'),
  ic_social: require('../icons/ic_social.png'),
  ic_success: require('../icons/ic_success.png'),
  ic_super: require('../icons/ic_super.png'),
  ic_twitter: require('../icons/ic_twitter.png'),
  ic_up: require('../icons/ic_up.png'),
  ic_user: require('../icons/ic_user.png'),
  ic_wifi: require('../icons/ic_wifi.png'),
  ic_work: require('../icons/ic_work.png'),
  ic_destination: require('../icons/ic_destination.png'),
}
export default images
